swagger: "2.0"
info:
  version: "1.0.0-preview20160930"
  title: Avalanche.Crash
  description: Microsoft Avalanche Crash REST API.

host: localhost:1337
basePath: /v0.1
schemes:
  - https

consumes:
  - application/json
produces:
  - application/json

paths:
  /crashes:
    post:
      description: API for notifying that a crash has been uploaded to storage for processing
      operationId: notifyCrash
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Array of uploaded crash location notifications
          required: true
          schema:
            type: array
            items: 
              $ref: "#/definitions/crash_ingestion_message"   
      responses:
        "200":
          description: Success
        "400":
          description: Error
          schema:
            $ref: "#/definitions/error_response"
      security:
        - Bearer: []
  /status:
    get:
      description: Returns the service status to the caller
      operationId: status
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/status_response"
        "400":
          description: Error
          schema:
            $ref: "#/definitions/error_response"

definitions:
  crash_ingestion_message:
    required:
      - app_id
      - app_start_timestamp
      - blob_url
      - id
      - ingest_timestamp
      - install_id
      - timestamp
    properties:
      app_id:
        description: The Identity of the Application
        type: string
        format: uuid
      blob_url: 
        description: The full URI including SASToken to blob storage
        type: string
      id:
        description: unique identifier for crash so can track problems in system
        type: string
        format: uuid
      timestamp:
        description: timestamp for error log
        type: string
        format: date-time
      ingest_timestamp:
        description: timestamp for error log reaching backend
        type: string
        format: date-time
      install_id:
        description: device installation id
        type: string
        format: uuid
      app_start_timestamp:
        description: app start timestamp
        type: string
        format: date-time

  status_response:
    required:
      - status
    properties:
      status:
        type: string

  error_response:
    required:
      - message
    properties:
      message:
        type: string
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header